name: Download the latest version from CTAN and push changes
on:
  push:
  fork:
  workflow_dispatch:

jobs:
  Update-from-CTAN:
    if: github.repository == 'DanySK/Template-ACM-Article'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: danysk/action-checkout@0.1.0
      - run: rm -r *
      - run: wget -U 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' https://portalparts.acm.org/hippo/latex_templates/acmart-primary.zip
      - run: unzip -o acmart-primary.zip
      - run: |
          cp -rlf acmart-primary/* .
          rm -rf acmart-primary
          ls -ahl samples/*i13n*
          rm -rf samples/*i13n*
          ls -ahl samples/
      - run: ls -ahl
      - run: sudo apt-get install -y texlive-latex-base texlive-latex-recommended texlive-fonts-extra texlive-xetex
      - run: make
      - run: latex acmart.ins
      - run: cp ACM-Reference-Format.bst samples/ACM-Reference-Format.bst
      - run: git add .
      - name: Commit files
        run: |
            git config --local user.email "danilo.pianini@unibo.it"
            git config --local user.name "Danilo Pianini disguised as a bot"
            git diff --quiet && git diff --staged --quiet || git commit -m "Pull changes from CTAN"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}
